{% set version = "0.1.5" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-rangemodelmetadata
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rangeModelMetadata_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rangeModelMetadata/rangeModelMetadata_{{ version }}.tar.gz
  sha256: 289620500522d489aafbb03c85f68182ef0a6701fed5f9d09b55fae337e2647b

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-bien
    - r-shiny
    - r-spocc
    - r-terra
  run:
    - r-base
    - r-bien
    - r-shiny
    - r-spocc
    - r-terra

test:
  commands:
    - $R -e "library('rangeModelMetadata')"           # [not win]
    - "\"%R%\" -e \"library('rangeModelMetadata')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=rangeModelMetadata
  license: GPL-3.0-or-later
  summary: 'Range Modeling Metadata Standards (RMMS) address three challenges: they (i) are designed for convenience to encourage use, (ii) accommodate a wide variety of applications, and (iii) are extensible to allow the community of range modelers to steer it as needed. RMMS are based on a data dictionary that specifies
    a hierarchical structure to catalog different aspects of the range modeling process. The dictionary balances a constrained, minimalist vocabulary to improve standardization with flexibility for users to provide their own values. Merow et al. (2019) <DOI:10.1111/geb.12993> describe the standards in more detail. Note that
    users who prefer to use the R package ''ecospat'' can obtain it from <https://github.com/ecospat/ecospat>.'
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
